### ISSUE TITLE
Populate repository with initial CC gem and dependencies

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dams5-cc-pilot#1]
Please create and populate the pilot repository Gemfile with the required base gems for a CC app.

**Comment by lsitu** [comment]
@mcritchlow  CC is upgraded to version1.6.1 now, while the version I used for practice is 1.5.0. Do you want me to try 1.6.1 to see whether it works? And also, would you like me to upload my codes for the Object resource in this ticket as well?

**Comment by mcritchlow** [comment]
@lsitu - Yes definitely to upgrading. I believe there have been some fairly significant changes between the versions.

The existing code you wrote for the Object class is fine. We can iterate or experiment with that as a starting point, if that works for the rest of the @ucsdlib/developers

**Comment by lsitu** [comment]
@mcritchlow Okay, I'll start from CC 1.6.1 to see whether it works.

**Comment by mcritchlow** [comment]
@lsitu if you/we encounter any bugs, we can file them in the CC repo (and provide fixes if possible). In general, we should try and stay on the very latest version, especially for this R&D

**Comment by lsitu** [comment]
@mcritchlow I think the latest version CC 1.6.1 looks good and I can set it up much more smoothly without any manipulation. I'll move ahead to customize with all the terms in our new data model and add my codes for customization in now.

**Comment by mcritchlow** [comment]
@lsitu - I believe this is done?

**Comment by lsitu** [comment]
@mcritchlow : Yes. I think we can close it now with the PR for overriding the default collection behavior being merged.

**Comment by mcritchlow** [comment]
@lsitu great, please mark as Closed then.
