### ISSUE TITLE
Create VM for pilot

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dams5-cc-pilot#12]
Please create a VM that can be used by @ucsdlib/developers to deploy the pilot CurationConcerns-based application as needed for demos, etc.

The VM will need, at a minimum, the prerequisites identified on the [CurationConcerns README](https://github.com/projecthydra/curation_concerns/#prerequisites)

**Comment by jhriv** [comment]
Ansible roles updated, and pushed to Galaxy. ffmpeg broke because of reliance upon static version numbers, role was refactored to screen-scrape for current version

**Comment by mcritchlow** [comment]
@jhriv - if this is done, can we close this out, pass along connection information for everyone via Slack, and then we can open additional tickets as needed for getting things deployed, etc.?

**Comment by mcritchlow** [comment]
Closing and will get John list of AD groups for access
