### ISSUE TITLE
What's the range for "type" property?

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/dams5-cc-pilot#18]
@ucsdlib/domm needs to discuss what the correct range for "type" is.
It's currently line 126 in the DD and listed as dc:DCMIType, which doesn't seem correct since we've developed a local type list with fun things like "notated movement"

**Comment by arwenhutt** [comment]
(I'm not able to assign labels to this, I think it might be a permission thing)

**Comment by arwenhutt** [comment]
Whoops, that was definitely user error ;)

**Comment by lsitu** [comment]
@arwenhutt: What's the different use for Type and Format (typeOfResource?)? It looks like the CVs are over wrapping.

**Comment by mcritchlow** [comment]
@arwenhutt let me look into the label permissions thing. sorry about that

**Comment by remerjohnson** [comment]
@arwenhutt: I've put the controlled values for our current `dams:typeOfResource` field into the CVs tab of the data dictionary under 'type'. I imagine we now change that range to Literal?

I think that works, but as @lsitu said, 'format' is... not so clear. Reading the DCMI spec, is this intended to be similar to what is captured now as `dams:formatName` (e.g. 'MP3') and `dams:duration`? Which I imagine PCDM captures somewhere else in the technical metadata? I can't think of a controlled value list for this that isn't likely captured somewhere else. 
[DC11 Format](http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=elements#format)

**Comment by mcritchlow** [comment]
@remerjohnson @lsitu - I wonder if we should setup a ticket to explicitly look into the technical metadata extracted by the CC stack for each of our known/common file types? Might that help clarify the issues noted above?

**Comment by lsitu** [comment]
@mcritchlow Yes, I think it's good to know about it first.
@remerjohnson Here is the technical metadata defined in CC for each file types: https://github.com/projecthydra/hydra-works/tree/master/lib/hydra/works/characterization/schema .

**Comment by mcritchlow** [comment]
@lsitu - 👍 

for the separate ticket, i was referring to actually running a few of each of our file types through CC and confirming the extracted technical metadata is populated as expected via FITS. But your schema link may be all @remerjohnson needs for now.

**Comment by mcritchlow** [comment]
#23 is setup for further investigation into technical metadata extraction.

**Comment by remerjohnson** [comment]
Okay. I do see in `base_schema.rb`, there is reference to `PREMIS.hasFormatName` which, when looking at the [ontology link](http://id.loc.gov/ontologies/premis.html#p_hasFormatName), doesn't specify what is expected, but I can assume those would basically be MIMEtypes? I guess we can just wait for the result of the test you set up in #23 
Thanks!

**Comment by remerjohnson** [comment]
Per meeting discussion, we agreed that the unresolved technical metadata issues from this ticket are contained in #23 and elsewhere.

Since we have good CVs for the range of "type" for @lsitu to work with, I'm closing this out.
