### ISSUE TITLE
Review Collection Membership branch of CC

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dams5-cc-pilot#22]
Per https://groups.google.com/forum/#!topic/hydra-tech/7_2jSVL8CNk

This would probably be important for us, in practice. It sounds like this branch will get merged eventually. Esme is guessing 2.0 given the breaking changes and keeping with semantic versioning, that makes sense. We may, if we start doing larger migration tests, want to try out using this branch. It would also allow us to provide feedback based on our experience.

**Comment by lsitu** [comment]
@mcritchlow : Yes, we have some big collections like SIO may have the same performance issue. I believe the performance will be improved a lot by linking it the other way from object to collection like what we do for dams in this case.

**Comment by VivianChu** [comment]
@escowles  -  I tried to use your branch member_of_replace for curation_concern and I got this error when creating object <ActiveFedora::UnknownAttributeError: unknown attribute 'member_of_collection_ids' for ObjectResource  Do you have any idea why that happened?  Do I need to add member_of_collection_ids somewhere to make it works?  Thanks

**Comment by VivianChu** [comment]
@escowles - Please disregard my questions.  I got it working. Thanks
