### ISSUE TITLE
Identify options for Wowza streaming with Fedora 4

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dams5-cc-pilot#27]
In DAMS4, the Wowza server is able to stream A/V files directly from our system because the files are transparently available on disk. We need to identify what our options are in a Fedora 4 environment, and the pros/cons of these options. This ticket may need to be an Epic, depending on further converstations w/ @ucsdlib/operations. Leaving this here as a placeholder for next Sprint.

**Comment by lsitu** [comment]
@rstanonik In Fedora 4, audio/video files are stored in the binary directory (fcrepo.binary.directory) with tree structure in binary format with no file extension. Have you found any ways for streaming files in binary format like that? Thanks.

**Comment by lsitu** [comment]
@rstanonik I just do a test to ingest a mp4 file to Fedora 4. It looks like that the jwplayer works well with the binary mp4 file in the binary store fcrepo.binary.directory: http://libraries/jwplayer-test/ffmpeg.html. So I think it could be just the pair path issue. Do you want to test it with Wowza? In fedora 4, the test mp4 file b5d2ca0af6cd70b361201236641d795cf9e94d29 (MessageDigest) will be stored with pair tree structure at  /PATH/TO/fcrepo.binary.directory/b5/d2/ca/b5d2ca0af6cd70b361201236641d795cf9e94d29.

**Comment by mcritchlow** [comment]
@lsitu and @rstanonik - given what Longshou demonstrated in the test URL, it appears that streaming F4 files from the binary store is possible. I think the next step would be changing out Wowza encrypted stream module to support the F4 convention. Longshou pushed the repo from Stash to Github and I created a [ticket to look into this](https://github.com/ucsdlib/encrypted-stream-name/issues/1). Thoughts/concerns?

**Comment by mcritchlow** [comment]
I'm going to close this out in favor of explicitly taking https://github.com/ucsdlib/encrypted-stream-name/issues/1 forward.
