### ISSUE TITLE
Overriding default Collection behavior

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dams5-cc-pilot#3]
- [ ] Overriding the default collection form with a minimum set of collection properties form the new data model like title, brief description, description, topic, publisher etc.
- [ ] Overriding the default behavior to display/show the properties from the form.
- [ ] Ensure that the edit form works as expected.

**Comment by mcritchlow** [comment]
@lsitu can you please help fill in the Description? I know you had some specific things you wanted to test out. Thanks.

**Comment by lsitu** [comment]
@mcritchlow I just added the description. Please review and correct me if I miss anything. Thanks.
