### ISSUE TITLE
Finalize template for CSV import

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/dams5-cc-pilot#35]
Need full spec for updated template for CSV import:
1. fields updated to D5 model
2. formatting/validation of column heads (loosen validation and/or simplify formatting)
3. validation rules for individual fields
4. validation rules for sheet as a whole

Related open questions: date handling https://github.com/ucsdlib/dams5-cc-pilot/issues/21, rights metadata and logic updated https://github.com/ucsdlib/dams5-cc-pilot/issues/36, ingest of headings using a URI instead of text, moving rights metadata into the spreadsheet (tickets to be added)

**Comment by mcritchlow** [comment]
@arwenhutt - per our discussion today re #37 Do you want to drop template iterations here for @lsitu to use going forward?

**Comment by arwenhutt** [comment]
Wait, do you mean in 35 or 37?

**Comment by mcritchlow** [comment]
Sorry, I meant in the Sprint meeting about #37 and next steps as it relates to this ticket.

**Comment by arwenhutt** [comment]
I'd like to save this issue for when we are closer to the end and creating the final version.  I'll plan on putting a draft here https://github.com/ucsdlib/dams5-cc-pilot/issues/39 .  But if there's a strong preference for otherwise, just let me know.

**Comment by mcritchlow** [comment]
Nope that's perfect 👍

**Comment by arwenhutt** [comment]
I didn't get to this on Friday, will try to get to it this afternoon after my meetings.

**Comment by lsitu** [comment]
Thanks @arwenhutt .

**Comment by mcritchlow** [comment]
This is mostly settled in Horton other than File Use which has a separate ticket setup for it. Closing in favor of any new tickets being done in Horton.
