### ISSUE TITLE
Implementation of the new rights metadata model in CC

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/dams5-cc-pilot#36]
While it was designed to simplify rights and access controls, the new rights management strategy and metadata model is significantly different then what we implemented in 4.  

Need a full spec including:
1. list of properties
2. associated application behavior (verified with the library rights policy group)
3. controlled value lists or validation rules for each property
4. properties and validation rules for entry via the CSV ingest stream
5. wireframe for entry via the MARC/AT ingest stream

Central to this, and a prerequisite before finalization of spec: 
- analysis of existing CC access controls (dev ticket?)
- depending on implementation the access controls related to QA and release to final access state (public, ucsd only, etc.)

**Comment by mcritchlow** [comment]
Of probably interest that we should all stay on top of. Might help us make some of these decisions:

https://groups.google.com/forum/#!topic/hydra-tech/1JAmGZnbfhM

**Comment by mcritchlow** [comment]
@ucsdlib/domm @lsitu - FYI I'm going to close this and port to Horton.
