### ISSUE TITLE
Review samples of CC access control metadata

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/dams5-cc-pilot#40]
Generate samples of access control metadata in CC

**Comment by lsitu** [comment]
@arwenhutt What's the scope of the sample access metadata you want to review, just some basic access metadata in CC, or something that has organizational customization? Will RDF/xml format work?

**Comment by lsitu** [comment]
@arwenhutt I've created the following examples for access control in RDF/XML format, which are the default visibilities in CC for Objects:
Open Access: [access-control-open.rdf.xml.txt](https://github.com/ucsdlib/dams5-cc-pilot/files/600707/access-control-open.rdf.xml.txt)

Your Institution (authenticated): [access-control-authenticated.rdf.xml.txt](https://github.com/ucsdlib/dams5-cc-pilot/files/600708/access-control-authenticated.rdf.xml.txt)

Embargoed: [access-control-embargoed.rdf.xml.txt](https://github.com/ucsdlib/dams5-cc-pilot/files/600709/access-control-embargoed.rdf.xml.txt)

Lease: [access-control-lease.rdf.xml.txt](https://github.com/ucsdlib/dams5-cc-pilot/files/600710/access-control-lease.rdf.xml.txt)

Private: [access-control-private.rdf.xml.txt](https://github.com/ucsdlib/dams5-cc-pilot/files/600711/access-control-private.rdf.xml.txt)

Please let me know if you have any questions.

**Comment by arwenhutt** [comment]
Thanks @lsitu - I think we can close this for now.  I'm presuming we'll need to look at Sufia instead now, but it'll be good to have these here in case we need to dive deeper beyond the Sufia layer when implementing access controls.

**Comment by lsitu** [comment]
@arwenhutt Yes. FYI, the access control metadata in Sufia is the same, and we've implemented the group access control in https://github.com/ucsdlib/dams5-cc-pilot/issues/44 for the Sufia base app [Horton](https://github.com/ucsdlib/horton), which is basing on Sufia 7.2.0. But the new merging app for CC/Sufia will be coming soon.
