### ISSUE TITLE
Add encrypted streaming support for A/V files via Wowza

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dams5-cc-pilot#43]
A ticket to pair with https://github.com/ucsdlib/encrypted-stream-name/issues/1

**Comment by lsitu** [comment]
I've added [PR](https://github.com/ucsdlib/horton/pull/9) as pair of https://github.com/ucsdlib/encrypted-stream-name/issues/1 to test the Wowza streaming support:
Enable Wowza streaming with JW Player:
*    config.wowza_enabled = true
Configure Wowza server url base:
*    config.wowza_baseurl = 'lib-streaming.ucsd.edu:1935/dams4-test/_definst_/'
Setting the environment key for encryption:
*    APPS_DHH_STREAMING_KEY
