### ISSUE TITLE
R&D: Ability to have Sufia ingest and CSV batch ingest live in same application

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dams5-cc-pilot#47]
Currently, Sufia (out of the box) has a single and multi-file based upload process. For our needs, we also need to port a CSV batch ingest into such an application. Please assess the potential challenges in having these two processes live side by side in a Sufia application, and identify and significant risks we should look at assessing prior to a full implementation.

**Comment by lsitu** [comment]
@mcritchlow I've created a [PR](https://github.com/ucsdlib/horton/issues/10) as the initial commit to demonstrate the support of CSV batch ingest that can live with Sufia ingest. Also we've got both server side files ingest with the browse-everything gem along with the option for local files selection.

**Comment by mcritchlow** [comment]
@lsitu - what are your thoughts on closing out this ticket? This was intentionally generic, and I'm thinking when we want to get more granular we'll do so in the Horton repo.

**Comment by lsitu** [comment]
@mcritchlow Yes, I'll close it now.
