### ISSUE TITLE
R&D: Evalute workflow support being added to Sufia/CC

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dams5-cc-pilot#48]
It appears that there is work ongoing in the community to add a workflow [1] system into curation concerns, and likely Sufia as well (probably via mediated deposit [2] as a default). Please investigate this and document what is being added. If possible, please also ask on hydra-tech or the Hydra slack channel what the timeline is for delivering this feature. 

1. https://github.com/projecthydra/curation_concerns/issues?q=is%3Aissue+is%3Aopen+label%3Aworkflow

2. https://github.com/projecthydra/sufia/labels/mediated%20deposit

**Comment by hweng** [comment]
In Sufia, a workflow is a state machine generated pragmatically by utilizing work done in a gem called Sipity (https://github.com/ndlib/sipity). Each workflow can look different depending on who has designed it.

The Initial workflow setup include the following steps:
1. Creating a workflow. 
2. Translating a workflow into JSON
3. Loading the workflow into the system

**Comment by hweng** [comment]
For us, the first step is to pull up a whiteboard or piece of paper and diagram out what you think a workflow should look like. 
Here are a few tips about drawing out a state machine:

- Draw circles or squares to describe a step in that workflow. (metadata review step, digitization review step, etc.)
- Draw lines in between these circles or squares to describe how to transition from one state to another.
- Determine the roles that are required by the user who would be taking an action.
- Determine which roles can see items throughout the workflow.
- When a state change occurs, what other actions could/should be taken?
Here is a quick example of a state machine that describes a workflow:
![image](https://cloud.githubusercontent.com/assets/2432753/21030217/3b57066a-bd52-11e6-8744-ddcffe32d1b3.png)

**Comment by hweng** [comment]
For the question: what the timeline is for delivering this feature?

Steve Van Tuyl has been leading this effort, He said "At this time, we seek to find out who might be able to contribute additional time from mid-December through mid-March.  The goal of these additional sprints would be to close out any outstanding issues that may be blocking the merge of core functionality for mediation and workflows in Sufia, continue to build functionality for multi-step workflows, and to help integrate the work being done for Mediated Deposit with parallel development sprints around Admin Sets and other new functionality. "
From https://groups.google.com/forum/#!topic/hydra-tech/h6E6noKI4no
https://groups.google.com/forum/#!topic/hydra-tech/5GEN6xR7n_4

@mcritchlow, please let me know if we would like to shoot him an email to help him out?  And Do we have bandwidth for the Jan-March sprints for it?

**Comment by mcritchlow** [comment]
Closing in favor of revisiting this in Horton when time allows. We have the two default workflows bundled in to the Horton app, and can work with @ucsdlib/domm to determine what is the best fit for our needs.
