### ISSUE TITLE
Review of rights model

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/dams5-cc-pilot#50]
Before implementation, review rights model to take into account 1) changes in community since it was originally drafted and 2) basic approach to access controls and rights in the chosen hydra head we are developing from.

Dependencies:
- Samples of existing access controls in hydra head we will be building on.

**Comment by mcritchlow** [comment]
@arwenhutt ijs this still relevant? If so, we should probably close and open a new ticket in horton.

**Comment by arwenhutt** [comment]
@mcritchlow I think this has been taken care of as part of other tickets/work.  If we run into any other issues we can open new tickets to address them.
