### ISSUE TITLE
R&D: Ordering of objects in CurationConcerns

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dams5-cc-pilot#6]
- [ ] Identify out-of-the-box functionality that would support our need for ordered objects and components
- [ ] Create sample records for Sprint demo of what is currently possible
- [ ] Document gaps in support that we would either need to build locally or work on in the community to support our complex object use cases

**Comment by VivianChu** [comment]
@mcritchlow I'm wondering if the component for our new complex object contain other fields like description, note, creator, subject, etc.. in addition to the title field and the technical metadata.  Thanks

**Comment by mcritchlow** [comment]
@VivianChu - good question. According to the new data model, components are just ucsd:Objects. I believe the intention is to have full descriptive metadata, etc. as we would with top level objects.

/cc @ucsdlib/domm as the implementation details of this might get interesting in areas where we want/need to distinguish between objects and components
