### ISSUE TITLE
Ask Princeton about Plum depedencies

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dams5-cc-pilot#7]
Contact Esme or Trey at Princeton and ask about:
- [ ] Kakadu software. Why did they choose it? What licensing model did they choose? Costs?
- [ ] Other IIIF support and needs that we could have in moving to a IIIF-based system for our images.

**Comment by lsitu** [comment]
@escowles: Could you tell us a little more about why Kakadu is chosen for Plum? What license model you chose and the cost for it?
We are interested in IIIF-based system as well. Do you know what other IIF support that we can consider as well. Thanks.

**Comment by escowles** [comment]
I think we are using Kakadu because it performs better than OpenJPEG, and didn't need to purchase a license to use it.  I asked with @jpstroop about it and he said he emailed and asked whether we needed to purchase a license or not, so I'd recommend doing that to see what they tell you.

We have downloaded the binaries from http://kakadusoftware.com/downloads/ and used them to generate our JP2s.  We then copy those to our Loris image server for serving them.

**Comment by jpstroop** [comment]
Just to follow up: [here](https://groups.google.com/d/msg/openjpeg/ugb2B66rHlY/PAzQZcW5BwAJ)'s some very recent benchmarking comparing Kakadu to OpenJPEG. That's why Kakadu ;-)

Kakadu is primarily interested in selling their SDK, but you're only likely to need the binaries in most cases. Just to get something on file, I would write to them and explain 1) that you only need the binaries and 2) that you're not using them for profit. Most of the time (they're a little frustrating this way) they just write back and say that's fine, and to be in touch if you ever need the SDK.

**Comment by mcritchlow** [comment]
@escowles @jpstroop thanks so much!

@lsitu - I can reach out to Kakadu to try and get something in writing. Should be fun.

/cc @jhriv re #12

**Comment by lsitu** [comment]
@escowles @jpstroop : Thank you very much for these information. It's really helpful. 

Esme, I try to download Kakadu for [OSX 10.11](http://kakadusoftware.com/wp-content/uploads/2014/06/KDU78_Demo_Apps_for_OSX1011_160322.dmg_.zip) and unzip it and I can't install it for that MacOSX 10.11 (El Capitan) issue. But I don't see the files kdu_compress and libkdu_v77R.dylib in Kakadu-app-demp.pkg (which is extracted from KDU78_Demo_Apps_for_OSX1011_160322 2.dmg). Do you know how to extract the binary files kdu_compress and libkdu_v77R.dylib?

**Comment by escowles** [comment]
@lsitu You need to unzip the Zip file and then mount the disk image that gets expanded.  Inside the disk image is a PKG you have to install by right clicking and selecting Open to get around the 'unknown developer' problem.  That PKG should install kdu_compress in /usr/local/bin and libkdu_v77R.dylib in /usr/local/lib.

**Comment by lsitu** [comment]
Thanks @escowles. I've tried several previously and now but I always get error "Kakadu Demonstration Apps for OSX10.11 can't be installed on this disk. These executables are compiled against the 10.11(EL Capitan) SDK ... "
So I think I may need to install it manually. I copied the pkg file Kakadu-demo-apps.pkg and run "xar -xf Kakadu-demo-apps.pkg" to unpack it. But I only see lots of .pkg files inside (including something similar kducompress.pkg and libkduv78r.pkg) but there are no files like kdu_compress and libkdu_v77R.dylib. How can I extract these two files in this case?

**Comment by escowles** [comment]
@lsitu It's weird that it won't install the files for you.  But once you unpack the PKG file, the files are gzipped and named `Payload` in each sub-package directory.  So you can ungzip them and put them where they need to go:

```
gunzip -c libkduv78r.pkg/Payload > /usr/local/lib/libkdu_v78R.dylib
gunzip -c kducompress.pkg/Payload > /usr/local/bin/kdu_compress
chmod a+x /usr/local/bin/kdu_compress
```

**Comment by lsitu** [comment]
I see. Thanks a lot @escowles.

**Comment by lsitu** [comment]
@escowles : Thanks for the instructions to install the binary for Kakadu. I installed it on my MAC (OS X 10.9.5) but it doesn't work. It looks like a binary compilation issue. Here is the error I got:
$ kdu_compress -v
-bash: /usr/local/bin/kdu_compress: cannot execute binary file

**Comment by escowles** [comment]
@lsitu The downloads page says "Built using Xcode 7 for OSX10.11 (El Capitan) and above", so I think you'll need to update to MacOSX 10.11 to use those binaries.  I don't see any links to older versions for pervious versions of MacOSX unfortunately.

**Comment by lsitu** [comment]
Yes, I think so. With the research and pilot project basing on CC for DAMS 5 on going, it's a little hard to make the decision to upgrade MacOSX at this time. Thanks @escowles .

**Comment by jpstroop** [comment]
@lsitu there's an older version of `kdu_expand` bundled with Loris you could try:
- bin: https://github.com/loris-imageserver/loris/blob/788faf509f087d9585228d1fe8b3a0f6b9293dc2/bin/Darwin/x86_64/kdu_expand
- lib: https://github.com/loris-imageserver/loris/blob/788faf509f087d9585228d1fe8b3a0f6b9293dc2/lib/Darwin/x86_64/libkdu_v73R.dylib

**Comment by jpstroop** [comment]
(But that won't help if you need `kdu_compress`). I guess you could try the older shared libraries with the newer binary--maybe you'd get lucky, but I doubt it.

**Comment by lsitu** [comment]
Thanks @jpstroop. Yes, it looks like it complains about kdu_compress at the first place. I was getting the same error after coping the libkdu_v73R.dylib downloaded from the link you provided above to/usr/local/lib/libkdu_v78R.dylib.
