### ISSUE TITLE
Identify and demo Sufia-specific features of interest for DAMS5

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dams5-cc-pilot#8]
Following the current feature checklist: https://wiki.duraspace.org/display/hydra/Built-in+Feature+Checklist+-+Merge+Working+Document

It would be nice to demo some of the Sufia-only features that may be of interest to us. This could also help us provide feedback to the group working on which features merge between the two systems, which are turned into feature toggles, which are made into separate gems, etc.

Of potential specific interest (though we can discuss priorities as needed):
- Batch Editing metadata
- Fixity checking
- Full-text indexing and searching
- Google Analytics integration
- Questioning Authority integartion
- ResourceSync capability

**Comment by hweng** [comment]
I've followed the Sufia's instruction to create a Sufia-based app. And when run generator to install sufia, I got the following error:
"Users/hweng/git/my_sufia_app/config/environments/development.rb:53:in `block in <top (required)>': uninitialized constant ActiveSupport::EventedFileUpdateChecker (NameError)"

And after comment out the above line of config, this error was gone. But it comes up another error.

**Comment by hweng** [comment]
@mcritchlow I've tried different versions of Sufia and Rails. The following combination Rails 4.2.7.1 with Sufia 7.1.0 works fine to me to get the sufia based app up and running. 
But I got issues when use sufia based app to create a new work object, which i posted the issue to hydra-tech list.

**Comment by mcritchlow** [comment]
@hweng - Thanks for the update. Hopefully folks on the list will be able to assist. But glad to hear you at least got a combination working.

**Comment by hweng** [comment]
@mcritchlow To follow up the above issue, Mike Giarlo replied me in hydra-tech list:
"Hi Huawei, 

OK, that helps. The error that you're seeing is resolved in the master branch of Sufia and will be released in 7.2.0, which should be released in the next week or so. Thanks for reporting this. 

-Mike "

**Comment by hweng** [comment]
@mcritchlow Then I tried the master branch but there is some issues to install sufia using the current readme steps.
Mike Giarlo told me that there are draft release notes for upgrading to 7.2.0 that include required steps. Those will be published soon when the release is cut.

**Comment by mcritchlow** [comment]
@hweng thanks for the update, that sounds about right. If there's a relevant Sufia ticket for this, would you mind referencing it here with a link?

**Comment by hweng** [comment]
@mcritchlow I didn't find particular relevant Sufia ticket for this issue. I get a reply from Justin said: this issue should be resolved with CurationConcerns 1.6.2, which I just released.  
I will try it late.

**Comment by hweng** [comment]
@mcritchlow  Here is the hydra-tech list link regarding this issue: https://groups.google.com/forum/#!topic/hydra-tech/6zq9KrUmKDw

**Comment by hweng** [comment]
@mcritchlow The above error got resolved with CurationConcerns 1.6.2, which Justin Coyne just released on last Friday.
I've tried creating some different type of objects. It works well for me.

**Comment by hweng** [comment]
@mcritchlow  For the new released Sufia v7.2.0, I’ve tested and got errors with its installations which I created the issue here: https://github.com/projecthydra/sufia/issues/2764

**Comment by hweng** [comment]
@mcritchlow Tested batch uploading files in Sufia v7.1.0, it works fine to me. But I got errors when try batch editing, and not sure if it get fixed in v7.2.0. I will try it in v7.2.0 after the above install errors get fixed.

**Comment by hweng** [comment]
@mcritchlow The sufia 7.2.0 install issue is resolved for me, see https://github.com/projecthydra/sufia/issues/2764#issuecomment-252138293

**Comment by mcritchlow** [comment]
Is this in progress? If so, please mark as such.

**Comment by mcritchlow** [comment]
@hweng - I'm thinking we can perhaps mark this as Closed, would you agree? I know 7.3 is coming out in the near future, and I suspect that might be a good time to look into the ability to add in more complex metadata, extend batch editing, integrate QA, etc. What are your thoughts?

**Comment by hweng** [comment]
@mcritchlow Yes, I agree it will be a good investment looking into 7.3, which I suspect it would be more solid and extended features.
