### ISSUE TITLE
Latest Blacklight features: alternate search results view(s)

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dams5-cc-pilot#9]
- Please identify if alternate Blacklight search results views (grid is of primary interest) are now available in the latest version of Blacklight.
- If more views are available, please be prepared to demo at the Sprint review meeting

**Comment by hweng** [comment]
@mcritchlow I've set up the blacklight version 6.0. The blacklight itself don't have alternate views, but I found that a gem blacklight-gallery which support for three alternate views: Gallery, Masonry and Slideshow views. 
I've installed it in blacklight app and it works fine for me in the standalone app.  But when I tried to install the blacklight  and blacklight-gallary gems to dams5-cc-pilot app, there are some conflicts.
Would you like to have a demo of the alternative views from local set up blacklight-demo? Or would you like me to go to the next step to implement the blacklight-gallary to our dams5 app?

**Comment by mcritchlow** [comment]
per discussion with @hweng. For this Sprint it would be nice to have a demo of the working alternate search result views either via the blacklight app or the dams5-cc-pilot app. If it can be integrated, that would be ideal, if not starting to identify the series of steps to get it integrated with a Curation Concerns app will be of value to us since we will definitely be using this plugin in our eventual dams5 production app.

**Comment by mcritchlow** [comment]
@hweng - I think, per your demo and the code being committed, this can be closed. Is that correct?

**Comment by hweng** [comment]
@mcritchlow, yes the overall function works fine to me. I think this ticket can be closed. For the detail CSS fix or update, it can be created in separate ticket when need.

**Comment by mcritchlow** [comment]
Great, please go ahead and close then.

**Comment by hweng** [comment]
@mcritchlow This new feature has been in feature branch. I've submitted a pull request for it and after it is merged into master, I will close this ticket.

**Comment by lsitu** [comment]
@hweng: I see two commits. It look like your older commit wasn't replaced correctly. Maybe you can do a rebase to remove the older (commit)[https://github.com/ucsdlib/dams5-cc-pilot/commit/79aebe135d3094a5385b2e1987fe25bb4f62f242]? Otherwise 👍

**Comment by hweng** [comment]
@lsitu There is actually only one commit in the pull request, would you check the pull request: https://github.com/ucsdlib/dams5-cc-pilot/pull/26

**Comment by lsitu** [comment]
@hweng Okay, got it. Just something strange here.

**Comment by hweng** [comment]
@lsitu Yeah, I think what showed here just the action history?

**Comment by lsitu** [comment]
Yes, different display from Jira that caught my attention.
